# Generated by Django 3.2.24 on 2024-03-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_product_manufactured_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='manufactured_at',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.TextField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Номер категории'),
        ),
    ]
