# Generated by Django 3.2.24 on 2024-03-19 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20240319_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views_count',
            new_name='views',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='views_count',
            new_name='views',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата_создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата создания'),
        ),
    ]
