# Generated by Django 3.2.24 on 2024-04-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0011_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия', 'verbose_name_plural': 'Версии'},
        ),
    ]
