# Generated by Django 3.2.24 on 2024-04-05 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_versionlistview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VersionListView',
        ),
    ]
